version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: terser
    versions:
    - 5.5.1
    - 5.6.0
    - 5.6.1
    - 5.7.0
  - dependency-name: eslint
    versions:
    - 7.25.0
  - dependency-name: react-intl
    versions:
    - 5.16.0
    - 5.17.0
  - dependency-name: gatsby-plugin-google-gtag
    versions:
    - 3.3.0
  - dependency-name: gatsby-image
    versions:
    - 3.3.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 3.3.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 4.3.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 4.3.0
  - dependency-name: gatsby-plugin-styled-components
    versions:
    - 4.3.0
  - dependency-name: babel-preset-gatsby
    versions:
    - 1.3.0
  - dependency-name: gatsby
    versions:
    - 3.2.1
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 3.2.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.2.0
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.20.0
  - dependency-name: gatsby-plugin-eslint
    versions:
    - 3.0.0
  - dependency-name: styled-components
    versions:
    - 5.2.2
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.16
    - 13.1.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
